#! /usr/bin/perl -w

my %emoji;

print "% Autogenerated from https://unicode.org/Public/emoji/13.0/emoji-test.txt"

while (<>) {
    if (/^([^;]*?)\s+;[^#]*#.*?E\S+(.*)/) {
	$codepts = $1;
	$name = $2;

	$name =~ s/\s+(\S)/uc($1)/ge;
	$name =~ s/[^A-Za-z]//g;
	if (exists $emoji{$name}) {
	    $s = 65;
	    while (exists $emoji{$name . chr($s)}) {
		$s++;
	    }
	    $name .= chr($s);
	}
	$codepts =~ s/\s+/~/g;
	printf("\\emoji_do:nn {%s}{%s}\n",$name, $codepts);
	$emoji{$name} = 1;
    }
}
